### ISSUE TITLE
Returns `:unrecognized_format` for valid git diff

### ISSUE THREAD

**Issue by joladev** [mononym/git_diff#1]
Calling `GitDiff.parse_patch/1` on the diff of Phoenix 1.4.9 and 1.4.10 results in `{:error, :unrecognized_format}`.

## Steps to reproduce

A diff that breaks the code can be found here https://gist.github.com/joladev/75b5b407cb0a39177943fdc0a6a90a94 or generated with `mix hex.package diff phoenix 1.4.9..1.4.10`.

**Comment by mononym** [comment]
I've been pretty busy lately and didn't notice someone had actually made some pull requests.

Glad someone found this useful! I'll take a look at the PR

**Comment by joladev** [comment]
I found some more stuff that wasn't supported and added it to the PR, so it does more than the description says
